# Generated by Django 5.2.5 on 2025-08-20 18:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('instructor', 'Instructor Report'), ('student', 'Student Report')], max_length=20)),
                ('attendance_status', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('avg_focus_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('focus_data_json', models.JSONField()),
                ('duration_seconds', models.IntegerField()),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to='report_charts/')),
                ('metadata', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='session.session')),
            ],
        ),
    ]
